apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - database_host=prod-db.example.com