apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: app-settings
  literals:
  - DATABASE_URL=localhost:5432
  - APP_PORT=8080

- name: app-config
  files:
  - config.json
  - settings.properties

secretGenerator:
- name: app-secrets
  literals:
  - api-key=my-secret-key
  - password=very-secret